language: python
python:
- 3.6
- 3.5
- 3.4
- 2.7
install:
- |
  if [ "$TEST_TYPE" = build ]; then
    pip install -e .[test]
  elif [ "$TEST_TYPE" = lint ]; then
    pip install flake8
  fi
script:
- |
  if [ "$TEST_TYPE" = lint ]; then
    echo "Checking Python code lint."
    flake8 all_badge
    exit
  elif [ "$TEST_TYPE" = build ]; then
    py.test --cov=all_badge all_badge
  fi
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
      coveralls
  fi
